# Generated by Django 6.0.6 on 2026-07-01 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentExcelApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='studentid',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_name',
            new_name='studentname',
        ),
    ]
